name: (Tests) and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log into DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish to Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push   : true
          tags   : coolenov/fusion-uanews-api:latest

      - name: Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@v2.6.1
        with:
          playbook: deploy.yml
          directory: ./
          key      : ${{ secrets.MY_KEY }}
          inventory: |
            [all]
            test_server ansible_host=${{ secrets.SERVER_HOST }} ansible_user=ubuntu ansible_password=${{secrets.ANSIBLE_BECOME_PASSWORD}}
          options: |
            --verbose
            --inventory .hosts


